### PR TITLE
[Grid] [Resolver] Asset Documnet and DataObject Resolver for Metadata should not throw a NotFoundException

### LINKED ISSUE #517: [Grid] [Resolver] Asset Documnet and DataObject Resolver for Metadata should not throw a NotFoundException
Should return null if element not found it could be just that the user do not have the permission to see the Element

### PR DESCRIPTION
**Pull request by martineiber**
## Changes in this pull request
Resolves #517

### CODE REVIEW

File: src/Grid/Column/Resolver/Metadata/DocumentResolver.php [hunk 1]
```diff
@@ -47,9 +48,13 @@ public function resolve(Column $column, ElementInterface $element): ColumnData
             return $this->getColumnData($column, null);
         }
 
-        $documentIndex = $this->documentService->getDocument(
-            reset($document['document'])
-        );
+        try {
+            $documentIndex = $this->documentService->getDocument(
```
Comment (lukmzig) [inline src/Grid/Column/Resolver/Metadata/DocumentResolver.php]: should we not call this $relatedDocument just for consistency? :)

**Review by lukmzig — APPROVED** [review]

File: src/Grid/Column/Resolver/Metadata/DocumentResolver.php (hunk 1 above)
Comment (martineiber) [reply src/Grid/Column/Resolver/Metadata/DocumentResolver.php]: Yeah sure makes sense :+1:

**Review by mattamon — APPROVED** [review]
🐺
