### PR TITLE
[Website Settings]: Update fails for type Text and field data

### LINKED ISSUE #1210: [Bug]: Website Settings - Update fails for type Text and field data
### Studio API version

latest

### Steps to reproduce

- create a website setting of type "text"
- update the "data" field of a website setting of type "Text" 

### Actual Behavior

Image

as you can see a string is not accepted from the backend

Image

### Expected Behavior

for the update to work without problems

### PR DESCRIPTION
**Pull request by lukmzig**
## Changes in this pull request
Resolves #1210 

## Additional info
Symfony maps data always to the object (ElementParameter) when using MapRequestPayload. 
Introduced custom denormalizer to tackle this issue.

### CODE REVIEW

File: src/WebsiteSetting/Request/WebsiteSettingsUpdateDenormalizer.php [hunk 1]
```diff
@@ -0,0 +1,77 @@
...
+use Pimcore\Bundle\StudioBackendBundle\Exception\Api\InvalidArgumentException;
+use Pimcore\Bundle\StudioBackendBundle\WebsiteSetting\Schema\ElementParameter;
+use Pimcore\Bundle\StudioBackendBundle\WebsiteSetting\Schema\WebsiteSettingsUpdate;
+use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
+use Symfony\Component\Serializer\Normalizer\NormalizerInterface;
+use function is_array;
+use function is_bool;
+use function is_string;
+
+final readonly class WebsiteSettingsUpdateDenormalizer implements DenormalizerInterface, NormalizerInterface
```
Comment (martineiber) [inline src/WebsiteSetting/Request/WebsiteSettingsUpdateDenormalizer.php:28]: Can be internal?

**Review by martineiber — CHANGES_REQUESTED** [review]

File: src/WebsiteSetting/Request/WebsiteSettingsUpdateDenormalizer.php (hunk 1 above)
Comment (lukmzig) [reply src/WebsiteSetting/Request/WebsiteSettingsUpdateDenormalizer.php:28]: yes, thanks :)

**Review by martineiber — APPROVED** [review]
