### PR TITLE
[Workflows] Schema

### LINKED ISSUE #555: Object Workflow
Image
I am getting an error response when trying to submit a workflow action for objects. 

here my api call with parameters:
Image

The class name of the object is "Car":
Image

Which is the same class name that the workflow is specified for:
Image

When I remove the condition of the workflow I am getting the below error:
Image
Which may suggest there is a problem with getting Workflows for objects?

Image
For consistency purposes we may want to use 'data-object' instead of 'object' here.

### PR DESCRIPTION
**Pull request by lukmzig**
## Changes in this pull request
Resolves #555 

## Additional info
- adapt schema to fit FE
- catch syntax error from symfony expression

### CODE REVIEW

File: src/Workflow/Schema/SubmitAction.php [hunk 1]
```diff
@@ -44,12 +44,12 @@ public function __construct(
...
-        #[Property(description: 'type of the element', type: 'string', example: ElementTypes::TYPE_OBJECT)]
+        #[Property(description: 'type of the element', type: 'string', example: ElementTypes::TYPE_DATA_OBJECT)]
         private string $elementType,
-        #[Property(description: 'name of the workflow', type: 'string', example: 'my_first_workflow')]
-        private string $workflowName,
-        #[Property(description: 'transition', type: 'string', example: 'start_workflow')]
-        private string $transition,
+        #[Property(description: 'id of the workflow', type: 'string', example: 'my_first_workflow')]
+        private string $workflowId,
+        #[Property(description: 'id of the transition', type: 'string', example: 'start_workflow')]
```
Comment (mattamon) [inline src/Workflow/Schema/SubmitAction.php]:
```suggestion
        #[Property(description: 'ID of the transition', type: 'string', example: 'start_workflow')]
```

Comment (lukmzig) [reply src/Workflow/Schema/SubmitAction.php]: Afaik we use id in the description of params ...
e.g
image

**Review by mattamon — APPROVED** [review]
🕺🏻 can't stop the feeling that this work flows
