### PR TITLE
[Data Object Editor] ValidationExceptions

### LINKED ISSUE #819: [Data Object Editor] Status code of ValidationExceptions
Pimcore throws for validation errors in a lot of cases a `ValidationException`, e.g. here:

https://github.com/pimcore/pimcore/blob/8ce5e6d9b83363a7e419de99ae4ed19f69a7ed6e/models/DataObject/ClassDefinition/Data/Input.php#L218

This is mainly relevant for the data object editor to validate mandatory fields and other types of validations. In the data object update endpoint this exception is handled the right way, so we get the error message etc. But could you please catch the 500 status code and send a different suitable one in the 400 range (e.g. 422)?

Don't know if it possible to handle this on your side on a very central place so that `ValidationException`s are handled always with the new status code. If yes, this would be a very good benefit - otherwise it should be respected at least in the update endpoint.

### PR DESCRIPTION
**Pull request by lukmzig**
## Changes in this pull request
Resolves #819 

## Additional info
- add new validation exception for editable fields
- add new translation key

### CODE REVIEW

File: src/Element/Service/ElementSaveService.php [hunk 1]
```diff
@@ -40,8 +39,7 @@ public function __construct(
     }
 
     /**
-     * @throws DuplicateFullPathException
-     * @throws Exception
+     * @inheritdoc
```
Comment (martineiber) [inline src/Element/Service/ElementSaveService.php]:
```suggestion
     * {@inheritdoc}
```
TBH i have no idea what's the difference, but docs says it should be with {}
https://manual.phpdoc.org/HTMLSmartyConverter/HandS/phpDocumentor/tutorial_tags.inlineinheritdoc.pkg.html

**Review by martineiber — APPROVED** [review]

File: src/Element/Service/ElementSaveService.php (hunk 1 above)
Comment (lukmzig) [reply src/Element/Service/ElementSaveService.php]: Hmm I did not see, that, at some places, e.g here we also have it like `inheritDoc`
https://github.com/pimcore/studio-backend-bundle/blob/1.x/src/Element/Service/ElementLocationService.php#L52

I will replace them to the format you posted

Comment (martineiber) [reply src/Element/Service/ElementSaveService.php]: At least we should keep it consistent...

Comment (lukmzig) [reply src/Element/Service/ElementSaveService.php]: now they should be consistent :)
